name: release PDF

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      
    - name: Build PDF
      run: docker run -v $PWD:/workdir paperist/alpine-texlive-ja latexmk main.tex

    - name: Upload PDF
      uses: softprops/action-gh-release@v1
      with:
        files: main.pdf
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
