name: Build PDF

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      
    - name: Build PDF
      run: docker run -v $PWD:/workdir paperist/alpine-texlive-ja latexmk main.tex

    - name: Release PDF
      uses: fnkr/github-action-ghr@v1
      env:
        GHR_PATH: main.pdf
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

